version: '3'

services:
  app:
    image: node:18.16.1-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn &&
        yarn start
      "
